#!/bin/csh -f

#Joe Atherton 30/01/19#

#run as source relion_keep_PHI_reset_angles_to_priors_and_shifts_to_0_relion3.csh fitted_angles.star where fitted_angles.star is the star file to be converted
#resets PSI and TILT to match PRIORS, KEEPING PHI. Also resets TRANSLATIONS to 0.

set star_file=$1

#copy headers to new file
echo ' ' > $star_file:r_reset_angles_to_priors.star
echo 'data_images' >> $star_file:r_reset_angles_to_priors.star
echo ' ' >> $star_file:r_reset_angles_to_priors.star
echo 'loop_' >> $star_file:r_reset_angles_to_priors.star

#copy column headers to new file
echo | grep '_rln*' $star_file >> $star_file:r_reset_angles_to_priors.star

#extract column data to temp file
echo | grep '.mrc' $star_file > $star_file:r_temp1.star


#print all data to new file 
echo | awk '{printf("%.6f\t%.6f\t%d\t%.6f\t%.6f\t%.6f\t%.6f\t%s\t%s\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%d\t%.6f\t%.6f\t%.6f\t%d\t%.6f\t%.6f\t%.6f\t%d\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, "'0.000000'", "'0.000000'", $25, $26, $4, $5, $29, $30, $31, $32, $33)}' $star_file:r_temp1.star >> $star_file:r_reset_angles_to_priors.star

rm -rf $star_file:r_temp1.star




































###########KAI ZHANG SCRIPTS#####################
#####**************************************************************************#####
#Despcription: This program is used to convert the box files in EMAN1 format to a relion star file
#Copyright@MRC-LMB
#Author: Kai Zhang
#Last Edit: 2014-4-11

#####**************************************************************************#####

#global setup for output format
#set KBold="\x1b\x5b1m"
#set KDefault="\x1b\x5b0m"
#set KUnderline="\x1b\x5b4m"
#set KFlash="\x1b\x5b5m"
#
#end of global setup
#
#set args = `printf "$argv" | wc | awk '{print $2}'`
#set Proc_name=`echo $0 | awk '{n=split($1,scr,"/");print scr[n];}'`
#
#if ( $args < 1 || $1 == '--help' || $1 == '-h' ) then
#
#
#	 printf "${KBold}Despcription: ${KDefault}This program is used to convert the box files in EMAN1 format (with tow additional column, class number and cross-correlation generated by AutoMatch) to a relion star file.\n"
#	 printf "	       Make sure the box file contains 6 columns, X, Y, Xsize, Ysize, Cross-correlation, ClassNumber.If the box files contain only X, Y, Xsize, Ysize, please use box2rl_XYonly.com instead.\n"
#	 printf "${KBold}example:${KDefault} $Proc_name  data_1???.box\n"
#
#	 exit(1)
#endif
#
#
#
#
#set i=1
#
#while ($i <= $args )
#
#set box=$argv[$i]
#set root=`basename $box .box`
#
#if ( -f ${root}.box  && -Z ${root}.box ) then
##<<< if 1001
#
#set starf=${root}_box2rl.star
#
#
#
#echo "convert $box to $starf "
#
#echo "" > $starf
#echo "data_" >> $starf
#echo "" >> $starf
#echo "loop_" >> $starf
#echo "_rlnCoordinateX #1" >> $starf
#echo "_rlnCoordinateY #2" >> $starf
#echo "_rlnClassNumber #3" >> $starf
#echo "_rlnAnglePsi #4" >> $starf
#echo "_rlnAutopickFigureOfMerit #5" >> $starf
#
#gawk '//{printf("%d\t%d\t%d\t%.6f\t%.6f\n", ($1+ $3/2)  , ($2 + $4/2), -999 , -999.000000, -999.000000)}' $box >>  $starf
#
#
#
#else
##<<< if 1001
#
#echo "$box does not exists, or zero size or wrong format or suffix not .box"
#
#endif
##>>> if 1001
#
#@ i++
#
#end
#
#
#exit
#
#




###################MY SCRIPTS################



#Source relion

#Convert .spi file, invert and normalise with eman2..
# 
#e2proc3d.py frealign_image_stack.spi frealign_image_stack.mrc --process=normalize.edgemean --mult=-1
#mv frealign_image_stack.mrc frealign_image_stack.mrcs
#
#
#Run the following
#
#relion_star_loopheader rlnImageName rlnMicrographName rlnDefocusU rlnDefocusV rlnDefocusAngle rlnVoltage rlnSphericalAberration rlnAmplitudeContrast > work_dir_1_13pf_25e-_DW_sf_1_frealign_seldec_8.star
#awk '{if ($1!="C") {print $1"@/d/emp2/u/ubjath01/100817_N_grub_CKK_doublewash_1-39Apix_tax_TSA_MTs/work_dir_1_13pf_25e-_DW_seamfind/chumps_round1/frealign_seldec/frealign_image_stack.mrcs", $8, $9, $10, $11, " 300 2.3 0.07"}  }' < work_dir_1_13pf_25e-_DW_sf_1_frealign_seldec_8.par >> work_dir_1_13pf_25e-_DW_sf_1_frealign_seldec_8.star
#
#Assuming the voltage is 300kV, the spherical aberration is 2.3 and the amplitude contrast is 0.07. Also, a single stack is assumed called: /d/emp2/u/ubjath01/100817_N_grub_CKK_doublewash_1-39Apix_tax_TSA_MTs/work_dir_1_13pf_25e-_DW_seamfind/chumps_round1/frealign_seldec/frealign_image_stack.mrcs.
#
#To get old frealign alignment params in too. Are the shifts in pixels or angstrom?:
#
#relion_star_loopheader rlnImageName rlnMicrographName rlnDefocusU rlnDefocusV rlnDefocusAngle rlnVoltage rlnSphericalAberration rlnAmplitudeContrast rlnMagnification rlnDetectorPixelSize rlnAngleRot rlnAngleTilt rlnAnglePsi rlnOriginX rlnOriginY > work_dir_1_13pf_25e-_DW_sf_1_frealign_seldec_0.star
#awk '{if ($1!="C") {print $1"@/d/emp2/u/ubjath01/100817_N_grub_CKK_doublewash_1-39Apix_tax_TSA_MTs/work_dir_1_13pf_25e-_DW_seamfind/chumps_round1/frealign_seldec/frealign_image_stack.mrcs", $8, $9, $10, $11, " 300.000000 2.300000 0.070000 3.597100e+04 5.000000", $4, $3, $2, $5, $6}  }' < work_dir_1_13pf_25e-_DW_sf_1_frealign_seldec_0.par >> work_dir_1_13pf_25e-_DW_sf_1_frealign_seldec_0.star
#
#Assuming the voltage is 300kV, the spherical aberration is 2.3, the amplitude contrast is 0.07, the real mag is 35971 and the detector pixel size is 5 microns. Also, a single stack is assumed called: /d/cm12/u/ubjath01/300616_cam1_ckk_1mgml_doublewash_TSA_taxol_MTs_polara_chuff/first_25e-_mc2_uncorrected/work_dir_1_13pf_ctff4_35e-seamfind/chumps_round1/frealign_sphi2/frealign_image_stack.spi.
#
#NOTE: Will need to invert the files when they go into relion. May need to use 'dont check norm option' particles should have been normed
#already...
#
##
##
##
##
#
#
#
#
#
